### ISSUE TITLE
Dataset is not available anymore

### ISSUE THREAD

**Issue by rguillome** [ulaval-damas/tree-bark-classification#2]
I was very happy to find this dataset because it's basically the only one. But unfortunately, it isn't reachable anymore due to a "closed state" in the Google Account behind.

**Comment by adrelino** [comment]
Any news on this? @marcelr

**Comment by yijinlee** [comment]
Original author has used MIT License for this, so I am happy to reupload the dataset zip file. However, it is ~32GB in size (32,511,480,193 bytes), so I will need someone to give me a host to upload it to... Thanks.

**Comment by Christopheraburns** [comment]
@yijinlee I can provide you with an S3 bucket to upload to.  Please let me know if you are able/willing and I will send you bucket URL and credentials.  Thanks!

**Comment by Christopheraburns** [comment]
@rguillome - did you ever get this dataset.  I could really use it to train a model
@yijinlee - any chance you still have this dataset and are willing to upload it to s3?
@gariepyalex - can you help?  We are looking for a copy of BarkNet 1.0

Thanks!

**Comment by ulavalrobotics** [comment]
We have updated the file pointer for the database. Here is the new link:

https://storage.googleapis.com/barknet-1/BarkNet1_0_Dataset.zip

We have updated the github page as well.

Sorry for the delay.

Philippe

**Comment by rguillome** [comment]
Hi,

Don't apologize ! This an amazing work, Thanks a lot !

**Comment by dvolgyes** [comment]
Hi, 

Would it be possible to share the corrected dataset, again? (not available anymore)

My recommendation would be to upload to zenodo.org:
https://zenodo.org/

It is a permanent storage for research data, free, handles uploads until 50GB without any questions,
provides a DOI for the data, and can link to the original article,
all authors/contributors can be credited with their ORCID IDs, and so on.

From user point of view: the links wouldn't expire anymore, and it has no cost.

**Comment by ulavalrobotics** [comment]
Dear David,

We are working on uploading the dataset on Zenodo. This being said, we checked and it is still available through the four links pointing to Mendeley Dataset, just not the google drive link.

Best regards,

Philippe

De : David Völgyes ***@***.***>
Envoyé : May 31, 2024 10:07 AM
À : ulaval-damas/tree-bark-classification ***@***.***>
Cc : Philippe Giguère ***@***.***>; Comment ***@***.***>
Objet : Re: [ulaval-damas/tree-bark-classification] Dataset is not available anymore (#2)


Hi,

Would it be possible to share the corrected dataset, again? (not available anymore)

My recommendation would be to upload to zenodo.org:
https://zenodo.org/

It is a permanent storage for research data, free, handles uploads until 50GB without any questions,
provides a DOI for the data, and can link to the original article,
all authors/contributors can be credited with their ORCID IDs, and so on.

From user point of view: the links wouldn't expire anymore, and it has no cost.
