### ISSUE TITLE
Paper results

### ISSUE THREAD

**Issue by AndersonCotrim** [ulaval-damas/tree-bark-classification#5]
I am having troubles to reproduce similar results as the paper, and now i notice that the images was resized to half dimensions and maybe this is my problem. Is the avaliable dataset processed with this, or the images need to be resized to get similar resultas as presented in the paper?

**Comment by ulavalrobotics** [comment]
The images are full resolution in the dataset. We reduced by half during training and testing. We did so as a) results were better with reduction b) we did not want to reduce the quality of the dataset.

So yes, you need to resize by half in your code.

Philippe Giguère, Ph.D.
Professeur, Département d'informatique et génie logiciel
Université Laval, Québec, Canada
